// Portable product-page render: JSON + template -> HTML string.
// Used by scripts/regen.mjs (Node, local) AND later by the CF Pages Function (Workers).
// Pure string templating — no Node/Workers-specific APIs.

export const CATMAP = {
  "mini": "Mini", "standard": "Standard", "standard-actuated": "Standard-Actuated",
  "standard-circular": "Standard-Circular", "performance-gen-1": "Performance-Gen-1",
  "performance-gen-3": "Performance-Gen-3", "enterprise": "Enterprise",
};

export function resolveImg(im, imgBase) {
  return im.key !== undefined ? imgBase + im.key : im.src;
}

// related = [{href,img,alt,title}] (auto-generated by caller, not stored in JSON)
export function render(prod, { template, imgBase, related }) {
  const e = prod.i18n.en;
  const slides = prod.images.map(im =>
    `\n                  <div class="swiper-slide feedback-single bg-white position-relative rounded"><img src="${resolveImg(im, imgBase)}" alt="${im.alt}" class="img-fluid" loading="lazy"></div>`
  ).join("") + "\n                ";
  const cards = related.map(c =>
    `\n              <div class="col-xl-3 col-lg-4 col-md-6">\n                <div class="blog-one__single">\n                  <a href="${c.href}">\n                    <div class="blog-one__img"><img src="${c.img}" alt="${c.alt}" loading="lazy"></div>\n                    <div class="blog-content"><h3 class="blog-one__title">${c.title}</h3></div>\n                  </a>\n                </div>\n              </div>`
  ).join("") + "\n            ";
  const summary = e.summary_html ? `<div class="item-explain">\n                ${e.summary_html}\n              </div>` : "";
  const robots = prod.robots ? `\n<meta name="robots" content="${prod.robots}">` : "";
  const reps = {
    META_TITLE: e.meta_title, KEYWORDS: e.keywords || "", META_DESC: e.meta_description,
    ROBOTS_META: robots, CANONICAL: `https://tejoy.com/${prod.category}/${prod.id}`,
    GALLERY_MAIN: slides, GALLERY_THUMB: slides, CATEGORY: CATMAP[prod.category] || prod.category,
    TITLE: e.title, SUMMARY_BLOCK: summary, DESCRIPTION: e.description_html,
    RELATED: cards, JSONLD_BREADCRUMB: prod.jsonld_breadcrumb || "", JSONLD_PRODUCT: prod.jsonld_product || "",
  };
  let r = template;
  for (const [k, v] of Object.entries(reps)) r = r.split(`{{${k}}}`).join(v);
  return r;
}

// Auto-generate up to 4 related: same-category first, then same-form-factor, then any.
export function genRelated(prod, allProducts, imgBase) {
  const byId = (a, b) => a.id - b.id;
  const others = Object.values(allProducts).filter(p => p.id !== prod.id);
  const sameCat = others.filter(p => p.category === prod.category).sort(byId);
  const sameForm = others.filter(p => p.category !== prod.category && p.form === prod.form).sort(byId);
  const rest = others.filter(p => p.category !== prod.category && p.form !== prod.form).sort(byId);
  return [...sameCat, ...sameForm, ...rest].slice(0, 4).map(s => {
    const im = s.images[0];
    return {
      href: `/${s.category}/${s.id}.html`,
      img: im ? resolveImg(im, imgBase) : "",
      alt: `${s.i18n.en.title} - tejoy Products`,
      title: s.i18n.en.title,
    };
  });
}
